/* Parity tests: the JS port against the Python original's outputs.
 *
 * Run with: node --test   (from the repo root; no dependencies)
 *
 * data/reference_results.json was generated by the PYTHON simulator
 * (src/simulator.py::_run, networkx edge betweenness) on the exact data
 * files this site ships. See README "Python parity" for the command.
 *
 * Because the two languages use different RNGs (NumPy PCG64 vs
 * cyrb53+mulberry32) AND consume draws differently (Python draws full
 * n×n matrices per step; JS draws per-edge), scenario-by-scenario equality
 * is not expected. The distributional checks below compare mean F over
 * 256 scenarios with an explicit tolerance instead.
 */
"use strict";

const { describe, it } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const sim = require(path.join(ROOT, "sim.js"));

const graphData = JSON.parse(fs.readFileSync(path.join(ROOT, "data/graph.json"), "utf8"));
const edgeParams = JSON.parse(fs.readFileSync(path.join(ROOT, "data/edge_params.json"), "utf8"));
const bestTheta = JSON.parse(fs.readFileSync(path.join(ROOT, "data/best_theta.json"), "utf8"));
const ref = JSON.parse(fs.readFileSync(path.join(ROOT, "data/reference_results.json"), "utf8"));

const graph = sim.loadGraph(graphData);
const base = {
  noise: Float64Array.from(edgeParams.params.map((p) => p[2])),
  p: Float64Array.from(edgeParams.params.map((p) => p[3])),
};
const N = graph.edges.length;
const TOL_MEAN_F = 2.0; // ~2.2x the SE of the mean difference at n=256
const TOL_EXACT = 1e-9;

describe("graph edges", () => {
  it("loads 40 nodes and 111 edges, matching the reference", () => {
    assert.equal(graph.n, 40);
    assert.equal(graph.n, ref.n_nodes);
    assert.equal(N, 111);
    assert.equal(N, ref.n_edges);
  });
  it("all edge endpoints are valid node indices", () => {
    for (const [u, v] of graph.edges) {
      assert.ok(Number.isInteger(u) && u >= 0 && u < graph.n, `bad u=${u}`);
      assert.ok(Number.isInteger(v) && v >= 0 && v < graph.n, `bad v=${v}`);
    }
  });
  it("edge list is in reference order (first and last edge spot check)", () => {
    assert.deepEqual(graph.edges[0], graphData.edges[0]);
    assert.deepEqual(graph.edges[N - 1], graphData.edges[N - 1]);
  });
});

describe("per-edge parameters", () => {
  it("shipped params reproduce the Python generator exactly", () => {
    // Verified when reference_results.json was generated:
    // max abs diff between data/edge_params.json and Python's
    // _per_edge_params(edges, n, 0.3, 0.25) is zero.
    assert.ok(ref.shipped_params_max_abs_diff_vs_python < 1e-12);
  });
  it("default env matches the reference header", () => {
    assert.equal(edgeParams.spreadP, 0.25);
    assert.equal(edgeParams.noiseAmp, 0.3);
    assert.equal(edgeParams.params.length, N);
    assert.equal(ref.edge_params.spreadP, 0.25);
    assert.equal(ref.edge_params.noiseAmp, 0.3);
  });
  it("noise and spread values are in valid ranges", () => {
    for (let i = 0; i < N; i++) {
      assert.ok(base.noise[i] >= 0, `noise[${i}] negative`);
      assert.ok(base.p[i] > 0 && base.p[i] <= 1, `p[${i}] out of range`);
    }
  });
});

describe("edge betweenness", () => {
  it("JS Brandes matches networkx up to the normalization constant", () => {
    // networkx returns normalized betweenness (÷ n(n-1)); the JS port is
    // unnormalized. guidedWeights() sum-normalizes, so only the ratios
    // matter — compare those to ~1e-9.
    const bet = sim.edgeBetweenness(graph.n, graph.edges);
    const sumJS = bet.reduce((a, b) => a + b, 0);
    const sumPy = ref.betweenness.reduce((a, b) => a + b, 0);
    assert.ok(sumJS > 0 && sumPy > 0);
    for (let i = 0; i < N; i++) {
      const d = Math.abs(bet[i] / sumJS - ref.betweenness[i] / sumPy);
      assert.ok(d < TOL_EXACT, `edge ${i}: ratio diff ${d}`);
    }
  });
});

describe("theta vector", () => {
  it("best_theta.json has one value per edge, all in [0, 1]", () => {
    assert.equal(bestTheta.length, N);
    for (let i = 0; i < N; i++) {
      assert.ok(bestTheta[i] >= 0 && bestTheta[i] <= 1, `theta[${i}]=${bestTheta[i]}`);
    }
  });
});

describe("objective formula", () => {
  it("F = cascade + 2*false_trips + 0.1*latency, exactly", () => {
    const m = { cascadeSize: 17, falseTrips: 5, latencyPenalty: 33.333 };
    assert.equal(sim.scenarioCost(m), 17 + 2 * 5 + 0.1 * 33.333);
  });
  it("oracle theta equals clip(noise + 0.10, 0, 1) on every edge", () => {
    // Python reference uses np.clip(noise + 0.10, 0, 1); JS uses
    // min(1, noise + 0.10). Shipped noise values are non-negative, so
    // both reduce to the same thing — verify on all 111 edges.
    for (let i = 0; i < N; i++) {
      const js = Math.min(1, base.noise[i] + 0.10);
      assert.ok(js >= 0 && js <= 1);
      assert.ok(Math.abs(js - Math.min(1, Math.max(0, base.noise[i] + 0.10))) < 1e-15);
    }
  });
});

describe("determinism", () => {
  it("same seed twice gives identical scenario cost", () => {
    const theta = new Array(N).fill(0.5);
    const a = sim.scenarioCost(sim.simulate(graph, base, theta, 12345));
    const b = sim.scenarioCost(sim.simulate(graph, base, theta, 12345));
    assert.equal(a, b);
  });
});

describe("mean-F distributional parity (256 seeds each)", () => {
  const strategies = {
    "fixed_0.5": new Array(N).fill(0.5),
    ga_best_theta: bestTheta,
    oracle: Array.from(base.noise, (x) => Math.min(1, x + 0.10)),
  };
  for (const [name, theta] of Object.entries(strategies)) {
    it(`${name}: |JS mean - Python mean| <= ${TOL_MEAN_F}`, () => {
      const seeds = sim.makeSeeds(256, 5000);
      const e = sim.evaluate(graph, base, theta, seeds, { cooldown: 5, nSteps: 40 });
      const py = ref.strategies.mean_F[name];
      assert.equal(py.n, 256);
      const delta = Math.abs(e.F - py.mean);
      assert.ok(
        delta <= TOL_MEAN_F,
        `${name}: JS mean ${e.F.toFixed(4)} vs Python ${py.mean.toFixed(4)} (delta ${delta.toFixed(4)})`
      );
      assert.ok(Number.isFinite(e.F) && !Number.isNaN(e.F), "non-finite mean F");
    });
  }
});
